version: '3.3'
services:
  dgraph-zero:
    ports:
      - '5080:5080'
      - '6080:6080'
    restart: unless-stopped
    image: ebdm/unigraph-dgraph
    command: dgraph zero --my=dgraph-zero:5080
  dgraph-alpha:
    ports:
      - '9080:9080'
      - '8080:8080'
    restart: unless-stopped
    image: ebdm/unigraph-dgraph
    command: dgraph alpha --my=dgraph-alpha:7080 --zero=dgraph-zero:5080
  backend:
    ports:
      - '3001:3001'
      - '4001:4001'
    environment:
      - DGRPAH_URL="dgraph-alpha:8080"
    image: ebdm/unigraph
    command: yarn backend-start
    depends_on:
      - dgraph-zero
      - dgraph-alpha
  frontend:
    ports:
      - '3000:3000'
    image: ebdm/unigraph
    command: yarn explorer-start
    depends_on:
      - backend